name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust the Node.js version if needed

    - name: Install dependencies
      run: npm install  # Using npm instead of yarn

    - name: Build the project
      run: npm run build  # This will build your project and output to the public directory

    - name: List files in the public directory
      run: ls -R ./public  # Lists all files in the public directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.WP_TOKEN }}  # Ensure you have this secret in your repository
        publish_dir: ./public
